# Generated by Django 3.1.4 on 2020-12-15 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ManyToApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Linguagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Programador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProgramadorLinguagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_conhecimento', models.IntegerField()),
                ('linguagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programador_linguagem', to='ManyToApp.linguagem')),
                ('programador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programador_linguagem', to='ManyToApp.programador')),
            ],
        ),
        migrations.AddField(
            model_name='linguagem',
            name='programadores',
            field=models.ManyToManyField(related_name='linguagens', through='ManyToApp.ProgramadorLinguagem', to='ManyToApp.Programador'),
        ),
    ]
