# Generated by Django 3.1.4 on 2020-12-17 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ManyToApp', '0003_carro_documentocpf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentocpf',
            name='pessoa',
        ),
        migrations.RemoveField(
            model_name='filmes',
            name='pessoas',
        ),
        migrations.RemoveField(
            model_name='linguagem',
            name='programadores',
        ),
        migrations.RemoveField(
            model_name='programadorlinguagem',
            name='linguagem',
        ),
        migrations.RemoveField(
            model_name='programadorlinguagem',
            name='programador',
        ),
        migrations.DeleteModel(
            name='Carro',
        ),
        migrations.DeleteModel(
            name='DocumentoCpf',
        ),
        migrations.DeleteModel(
            name='Filmes',
        ),
        migrations.DeleteModel(
            name='Linguagem',
        ),
        migrations.DeleteModel(
            name='Programador',
        ),
        migrations.DeleteModel(
            name='ProgramadorLinguagem',
        ),
    ]
