# Generated by Django 3.1.4 on 2021-03-08 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManyToApp', '0007_p_fisica_p_juridica'),
    ]

    operations = [
        migrations.AddField(
            model_name='carro',
            name='data_compra',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
