# Generated by Django 3.1.4 on 2021-03-08 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManyToApp', '0008_carro_data_compra'),
    ]

    operations = [
        migrations.AddField(
            model_name='carro',
            name='info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
